(()=>{
  const weapons=window.WEAPONS||[],state={items:[]};
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function credit(){const saved=JSON.parse(localStorage.getItem('skillAllocation')||'{}'),add=Number(saved.allocations?.credit?.occupation||0)+Number(saved.allocations?.credit?.interest||0);return Math.min(99,add)}
  function assets(cr){if(cr===0)return {level:'身无分文',cash:'$0.50',assets:'没有',spend:'$0.50'};if(cr<=9)return {level:'拮据',cash:'$'+cr,assets:'$'+cr*10,spend:'$2'};if(cr<=49)return {level:'标准',cash:'$'+cr*2,assets:'$'+cr*50,spend:'$10'};if(cr<=89)return {level:'小康',cash:'$'+cr*5,assets:'$'+cr*500,spend:'$50'};if(cr<=98)return {level:'富裕',cash:'$'+cr*20,assets:'$'+cr*2000,spend:'$250'};return {level:'富豪',cash:'$50,000',assets:'$5,000,000+',spend:'$5,000'}}
  function create(){const nav=$('.steps');if(!$('#n6'))nav.insertAdjacentHTML('beforeend','<span id="n6"><b>6</b> 资产与装备</span>');if(!$('#s6'))$('main').insertAdjacentHTML('beforeend','<section class="screen" id="s6"></section>')}
  function typeOptions(){return ['全部类型',...new Set(weapons.map(w=>w.type))].map(x=>'<option>'+esc(x)+'</option>').join('')}
  function filtered(){const type=$('#weaponType')?.value||'全部类型',q=($('#weaponSearch')?.value||'').trim().toLowerCase();return weapons.filter(w=>(type==='全部类型'||w.type===type)&&(!q||w.name.toLowerCase().includes(q)||String(w.skill).toLowerCase().includes(q)))}
  function fillList(){const list=$('#weaponOptions');if(list)list.innerHTML=filtered().map(w=>'<option value="'+esc(w.name)+'">'+esc(w.type)+' · '+esc(w.skill)+'</option>').join('')}
  function selectedWeapon(){const name=$('#weaponSearch').value.trim(),pool=filtered();return pool.find(w=>w.name===name)||weapons.find(w=>w.name===name)}
  function preview(){const w=selectedWeapon(),box=$('#weaponPreview');if(!w){box.innerHTML='<span>输入或选择武器后，这里会显示标准规则数据。</span>';return}box.innerHTML='<b>'+esc(w.name)+'</b><span>'+esc(w.type)+' · '+esc(w.skill)+'</span><span>伤害 '+esc(w.damage)+'　射程 '+esc(w.range)+'　故障 '+esc(w.malfunction)+'</span>'}
  function add(){const w=selectedWeapon();if(!w){$('#equipmentStatus').textContent='请从标准武器列表中选择一项。';return}state.items.push({...w,displayName:w.name});$('#weaponSearch').value='';renderRows();preview()}
  function renderRows(){const body=$('#equipmentRows');body.innerHTML=state.items.length?state.items.map((w,i)=>'<tr><td><input data-name="'+i+'" value="'+esc(w.displayName)+'" aria-label="自定义显示名称"></td><td>'+esc(w.name)+'</td><td>'+esc(w.type)+'</td><td>'+esc(w.skill)+'</td><td>'+esc(w.damage)+'</td><td>'+esc(w.range)+'</td><td>'+esc(w.impale)+'</td><td>'+esc(w.attacks)+'</td><td>'+esc(w.ammo)+'</td><td>'+esc(w.malfunction)+'</td><td><button data-remove="'+i+'">×</button></td></tr>').join(''):'<tr><td colspan="11" class="equipment-empty">尚未携带武器</td></tr>';body.querySelectorAll('[data-name]').forEach(x=>x.oninput=e=>state.items[Number(e.target.dataset.name)].displayName=e.target.value);body.querySelectorAll('[data-remove]').forEach(x=>x.onclick=e=>{state.items.splice(Number(e.target.dataset.remove),1);renderRows()})}
  function save(){localStorage.setItem('equipment',JSON.stringify({credit:credit(),weapons:state.items}));$('#equipmentStatus').textContent='资产与武器已保存，正在生成简化调查员卡。';go(7);renderSummaryCard()}
  function render(){const cr=credit(),a=assets(cr),saved=JSON.parse(localStorage.getItem('equipment')||'{}');if(!state.items.length&&saved.weapons)state.items=saved.weapons;$('#s6').innerHTML='<div class="equipment-head"><div><span class="eyebrow">STEP 06 · ASSETS & EQUIPMENT</span><h1>资产与装备</h1><p>信用评级决定生活水平与资产；武器规则数据始终来自标准条目。</p></div><button class="skill-back" type="button" onclick="go(5)">← 返回技能分配</button></div><div class="asset-summary"><div><small>信用评级</small><b>'+cr+'</b></div><div><small>生活水平</small><b>'+a.level+'</b></div><div><small>现金</small><b>'+a.cash+'</b></div><div><small>其他资产</small><b>'+a.assets+'</b></div><div><small>消费水平</small><b>'+a.spend+'</b></div></div><div class="weapon-picker"><div class="weapon-controls"><label>先按类型筛选<select id="weaponType">'+typeOptions()+'</select></label><label>搜索或选择标准武器<input id="weaponSearch" list="weaponOptions" placeholder="输入武器名称或关键词" autocomplete="off"><datalist id="weaponOptions"></datalist></label><button class="btn" id="addWeapon" type="button">加入武器</button></div><div class="weapon-preview" id="weaponPreview"></div></div><div class="equipment-table-wrap"><table class="equipment-table"><thead><tr><th>显示名称</th><th>标准武器</th><th>类型</th><th>使用技能</th><th>伤害</th><th>射程</th><th>贯穿</th><th>次数</th><th>装弹量</th><th>故障值</th><th></th></tr></thead><tbody id="equipmentRows"></tbody></table></div><div class="equipment-actions"><button class="btn" id="saveEquipment" type="button">保存并生成调查员卡</button><span id="equipmentStatus">可修改显示名称，其他规则数据不可编辑。</span></div>';$('#weaponType').onchange=()=>{fillList();preview()};$('#weaponSearch').oninput=()=>{fillList();preview()};$('#addWeapon').onclick=add;$('#saveEquipment').onclick=save;fillList();preview();renderRows()}
  create();window.renderEquipment=render;
})();
